apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-bp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend-bp
  template:
    metadata:
      labels:
        app: frontend-bp
    spec:
      containers:
        - name: frontend-bp
          image: us.icr.io/clstr/frontend-bp
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-bp
  labels:
    app: frontend-bp
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: frontend-bp
